export function getChatPanelHtml(figureCode: string): string {
  const tikzJson = JSON.stringify(figureCode);

  return [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="UTF-8">',
    '<meta http-equiv="Content-Security-Policy" content="default-src \'none\'; script-src \'unsafe-inline\'; style-src \'unsafe-inline\'; img-src data:;">',
    '<title>Proof Diagram Chat</title>',
    '<style>',
    '* { margin: 0; padding: 0; box-sizing: border-box; }',
    'body { background: #f7f7f5; color: #1a1a1a; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; height: 100vh; display: flex; flex-direction: column; overflow: hidden; }',
    '.header { display: flex; align-items: center; justify-content: space-between; padding: 10px 16px; background: #fff; border-bottom: 1px solid #e5e5e3; flex-shrink: 0; }',
    '.header-title { display: flex; align-items: center; gap: 8px; font-size: 13px; font-weight: 600; color: #1a1a1a; }',
    '.header-dot { width: 8px; height: 8px; background: #6366f1; border-radius: 50%; }',
    '.main { flex: 1; display: flex; flex-direction: column; overflow: hidden; }',
    '.chat-section { flex: 0 0 33%; display: flex; flex-direction: column; overflow: hidden; border-bottom: 1px solid #e5e5e3; }',
    '.chat-history { flex: 1; overflow-y: auto; padding: 14px 16px; display: flex; flex-direction: column; gap: 10px; }',
    '.input-section { padding: 10px 16px; background: #fff; border-top: 1px solid #e5e5e3; border-bottom: 1px solid #e5e5e3; flex-shrink: 0; }',
    '.input-wrapper { display: flex; align-items: center; background: #f7f7f5; border: 1.5px solid #e5e5e3; border-radius: 10px; padding: 8px 12px; gap: 8px; transition: border-color 0.15s; }',
    '.input-wrapper:focus-within { border-color: #6366f1; background: #fff; }',
    '.input-wrapper input { flex: 1; border: none; background: transparent; font-size: 13px; font-family: inherit; color: #1a1a1a; outline: none; }',
    '.input-wrapper input::placeholder { color: #b0b0b0; }',
    '.send-btn { width: 28px; height: 28px; background: #6366f1; border: none; border-radius: 7px; cursor: pointer; display: flex; align-items: center; justify-content: center; flex-shrink: 0; transition: background 0.15s; }',
    '.send-btn:hover { background: #4f46e5; }',
    '.send-btn:disabled { background: #d4d4f7; cursor: not-allowed; }',
    '.send-btn svg { width: 14px; height: 14px; fill: white; }',
    '.work-block { background: #fff; border: 1px solid #e5e5e3; border-radius: 10px; padding: 10px 14px; font-family: "SF Mono", "Fira Code", "Courier New", monospace; font-size: 11.5px; display: flex; flex-direction: column; gap: 4px; }',
    '.work-line { display: flex; align-items: center; gap: 8px; color: #555; opacity: 0; transform: translateY(4px); transition: opacity 0.2s ease, transform 0.2s ease; }',
    '.work-line.visible { opacity: 1; transform: translateY(0); }',
    '.work-line .icon { font-size: 11px; width: 14px; text-align: center; flex-shrink: 0; }',
    '.work-line.done .icon { color: #22c55e; }',
    '.work-line.running .icon { color: #6366f1; }',
    '.work-line.pending .icon { color: #b0b0b0; }',
    '.work-line .text { color: #444; }',
    '.cursor { display: inline-block; width: 6px; height: 13px; background: #6366f1; border-radius: 1px; animation: blink 1s step-end infinite; vertical-align: middle; margin-left: 2px; }',
    '@keyframes blink { 0%,100%{opacity:1} 50%{opacity:0} }',
    '.user-msg { align-self: flex-end; background: #6366f1; color: white; padding: 8px 13px; border-radius: 14px 14px 3px 14px; font-size: 13px; max-width: 85%; line-height: 1.4; }',
    '.error-msg { font-size: 12px; padding: 8px 12px; background: #fef2f2; border: 1px solid #fecaca; border-radius: 8px; color: #dc2626; }',
    '.diagrams-section { flex: 0 0 57%; display: flex; overflow: hidden; }',
    '.diagram-panel { flex: 1; display: flex; flex-direction: column; overflow: hidden; position: relative; }',
    '.diagram-panel:first-child { border-right: 1px solid #e5e5e3; }',
    '.diagram-panel-header { padding: 7px 12px; background: #fff; border-bottom: 1px solid #e5e5e3; font-size: 10px; font-weight: 600; color: #888; text-transform: uppercase; letter-spacing: 0.6px; flex-shrink: 0; }',
    '.diagram-panel-body { flex: 1; display: flex; align-items: center; justify-content: center; overflow: auto; padding: 12px; background: #fff; position: relative; }',
    '.diagram-panel-body img.png-preview { max-width: 100%; height: auto; border-radius: 4px; transition: opacity 0.3s; }',
    '.diagram-empty { color: #ccc; font-size: 12px; text-align: center; line-height: 1.6; }',
    '.pdf-error { font-size: 11px; color: #dc2626; padding: 8px; background: #fef2f2; border-radius: 6px; text-align: center; }',
    '.hover-overlay { position: absolute; inset: 0; background: rgba(255,255,255,0.88); display: flex; align-items: center; justify-content: center; opacity: 0; transition: opacity 0.18s ease; pointer-events: none; }',
    '.diagram-panel-body:hover .hover-overlay { opacity: 1; pointer-events: all; }',
    '.hover-btn { background: #6366f1; color: white; border: none; border-radius: 8px; padding: 8px 16px; font-size: 12px; font-weight: 500; cursor: pointer; font-family: inherit; transition: background 0.15s; }',
    '.hover-btn:hover { background: #4f46e5; }',
    '::-webkit-scrollbar { width: 5px; height: 5px; }',
    '::-webkit-scrollbar-track { background: transparent; }',
    '::-webkit-scrollbar-thumb { background: #ddd; border-radius: 3px; }',
    '</style>',
    '</head>',
    '<body>',
    '<div class="header">',
    '  <div class="header-title"><div class="header-dot"></div>Proof Diagram Chat<\/div>',
    '<\/div>',
    '<div class="main">',
    '  <div class="chat-section">',
    '    <div class="chat-history" id="chatHistory"><\/div>',
    '  <\/div>',
    '  <div class="input-section">',
    '    <div class="input-wrapper">',
    '      <input type="text" id="userInput" placeholder="Describe an adjustment... e.g. make the cones blue" \/>',
    '      <button class="send-btn" id="sendBtn"><svg viewBox="0 0 24 24"><path d="M2 21l21-9L2 3v7l15 2-15 2v7z"\/><\/svg><\/button>',
    '    <\/div>',
    '  <\/div>',
    '  <div class="diagrams-section">',
    '    <div class="diagram-panel">',
    '      <div class="diagram-panel-header">Before<\/div>',
    '      <div class="diagram-panel-body" id="beforeBody">',
    '        <div class="diagram-empty" id="beforeEmpty">No previous version<\/div>',
    '        <div class="hover-overlay">',
    '          <button class="hover-btn" id="beforeBtn">Get Image Code<\/button>',
    '        <\/div>',
    '      <\/div>',
    '    <\/div>',
    '    <div class="diagram-panel">',
    '      <div class="diagram-panel-header">After<\/div>',
    '      <div class="diagram-panel-body" id="afterBody">',
    '        <div class="diagram-empty" id="afterEmpty">Compiling preview...<\/div>',
    '        <div class="hover-overlay">',
    '          <button class="hover-btn" id="afterBtn">Get Image Code<\/button>',
    '        <\/div>',
    '      <\/div>',
    '    <\/div>',
    '  <\/div>',
    '<\/div>',
    '<script>',
    '  const vscode = acquireVsCodeApi();',
    '  let beforeTikz = null;',
    '  let afterTikz = ' + tikzJson + ';',
    '',
    '  const WORK_LINES_INITIAL = [',
    '    "Parsing proof structure...",',
    '    "Extracting variables and notation...",',
    '    "Identifying geometric objects...",',
    '    "Generating TikZ diagram...",',
    '    "Compiling preview..."',
    '  ];',
    '  const WORK_LINES_ADJUST = [',
    '    "Reading current diagram...",',
    '    "Parsing adjustment request...",',
    '    "Applying changes to TikZ...",',
    '    "Compiling updated preview..."',
    '  ];',
    '',
    '  function renderPng(base64, bodyId, emptyId) {',
    '    const body = document.getElementById(bodyId);',
    '    const empty = document.getElementById(emptyId);',
    '    if (empty) { empty.remove(); }',
    '    const old = body.querySelector("img.png-preview, .pdf-error");',
    '    if (old) { old.remove(); }',
    '    const img = document.createElement("img");',
    '    img.className = "png-preview";',
    '    img.src = "data:image/png;base64," + base64;',
    '    body.insertBefore(img, body.querySelector(".hover-overlay"));',
    '  }',
    '',
    '  function showWorkBlock(lines, onComplete) {',
    '    const history = document.getElementById("chatHistory");',
    '    const block = document.createElement("div");',
    '    block.className = "work-block";',
    '    lines.forEach(function(text) {',
    '      const line = document.createElement("div");',
    '      line.className = "work-line pending";',
    '      line.innerHTML = "<span class=\'icon\'>&#8942;<\/span><span class=\'text\'>" + text + "<\/span>";',
    '      block.appendChild(line);',
    '    });',
    '    history.appendChild(block);',
    '    history.scrollTop = history.scrollHeight;',
    '    const lineEls = block.querySelectorAll(".work-line");',
    '    let i = 0;',
    '    function showNext() {',
    '      if (i > 0) {',
    '        lineEls[i-1].classList.remove("running");',
    '        lineEls[i-1].classList.add("done");',
    '        lineEls[i-1].querySelector(".icon").textContent = "✓";',
    '      }',
    '      if (i >= lineEls.length) { if (onComplete) { onComplete(); } return; }',
    '      const el = lineEls[i];',
    '      el.classList.remove("pending");',
    '      el.classList.add("running", "visible");',
    '      el.querySelector(".icon").innerHTML = "<span class=\'cursor\'><\/span>";',
    '      history.scrollTop = history.scrollHeight;',
    '      i++;',
    '      setTimeout(showNext, 380);',
    '    }',
    '    showNext();',
    '  }',
    '',
    '  function addUserMessage(text) {',
    '    const history = document.getElementById("chatHistory");',
    '    const el = document.createElement("div");',
    '    el.className = "user-msg";',
    '    el.textContent = text;',
    '    history.appendChild(el);',
    '    history.scrollTop = history.scrollHeight;',
    '  }',
    '',
    '  function promoteAfterToBefore() {',
    '    if (!afterTikz) { return; }',
    '    beforeTikz = afterTikz;',
    '    const beforeBody = document.getElementById("beforeBody");',
    '    const empty = document.getElementById("beforeEmpty");',
    '    if (empty) { empty.remove(); }',
    '    const old = beforeBody.querySelector("img.png-preview");',
    '    if (old) { old.remove(); }',
    '    const afterImg = document.getElementById("afterBody").querySelector("img.png-preview");',
    '    if (afterImg) {',
    '      const clone = afterImg.cloneNode(true);',
    '      beforeBody.insertBefore(clone, beforeBody.querySelector(".hover-overlay"));',
    '    }',
    '  }',
    '',
    '  function sendMessage() {',
    '    const input = document.getElementById("userInput");',
    '    const text = input.value.trim();',
    '    if (!text) { return; }',
    '    input.value = "";',
    '    document.getElementById("sendBtn").disabled = true;',
    '    addUserMessage(text);',
    '    promoteAfterToBefore();',
    '    showWorkBlock(WORK_LINES_ADJUST, null);',
    '    vscode.postMessage({ type: "adjustDiagram", text: text });',
    '  }',
    '',
    '  // ── Button wiring ──',
    '  document.getElementById("sendBtn").addEventListener("click", sendMessage);',
    '  document.getElementById("userInput").addEventListener("keydown", function(e) { if (e.key === "Enter") { sendMessage(); } });',
    '  document.getElementById("beforeBtn").addEventListener("click", function() {',
    '    if (beforeTikz) { vscode.postMessage({ type: "openCodePanel", tikz: beforeTikz }); }',
    '  });',
    '  document.getElementById("afterBtn").addEventListener("click", function() {',
    '    if (afterTikz) { vscode.postMessage({ type: "openCodePanel", tikz: afterTikz }); }',
    '  });',
    '',
    '  window.addEventListener("message", function(event) {',
    '    const msg = event.data;',
    '    if (msg.type === "pdfPreview") {',
    '      document.getElementById("sendBtn").disabled = false;',
    '      renderPng(msg.pdfBase64, "afterBody", "afterEmpty");',
    '    }',
    '    if (msg.type === "newDiagram") { afterTikz = msg.tikz; }',
    '    if (msg.type === "compiling") {',
    '      const img = document.getElementById("afterBody").querySelector("img.png-preview");',
    '      if (img) { img.style.opacity = "0.4"; }',
    '    }',
    '    if (msg.type === "pdfError") {',
    '      document.getElementById("sendBtn").disabled = false;',
    '      const body = document.getElementById("afterBody");',
    '      const old = body.querySelector("img.png-preview, .pdf-error");',
    '      if (old) { old.remove(); }',
    '      const err = document.createElement("div");',
    '      err.className = "pdf-error";',
    '      err.textContent = msg.text;',
    '      body.insertBefore(err, body.querySelector(".hover-overlay"));',
    '    }',
    '    if (msg.type === "error") {',
    '      document.getElementById("sendBtn").disabled = false;',
    '      const history = document.getElementById("chatHistory");',
    '      const el = document.createElement("div");',
    '      el.className = "error-msg";',
    '      el.textContent = "Error: " + msg.text;',
    '      history.appendChild(el);',
    '      history.scrollTop = history.scrollHeight;',
    '    }',
    '  });',
    '',
    '  window.addEventListener("load", function() {',
    '    showWorkBlock(WORK_LINES_INITIAL, null);',
    '  });',
    '<\/script>',
    '</body>',
    '</html>',
  ].join('\n');
}